// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs072h5jpe1nC-3dZMvxtUHjM44QYk3B0',
    appId: '1:420920607861:web:3d465993e409513b92643c',
    messagingSenderId: '420920607861',
    projectId: 'muzika-plus',
    authDomain: 'muzika-plus.firebaseapp.com',
    storageBucket: 'muzika-plus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ8QWGsa919K4eYQAyp1r0drdzAWQQW1o',
    appId: '1:420920607861:android:d407adf1ad91d58092643c',
    messagingSenderId: '420920607861',
    projectId: 'muzika-plus',
    storageBucket: 'muzika-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_G-Auws0uc69CS1Fpmt4fxcp7TNYhreE',
    appId: '1:420920607861:ios:c33a711f31c5290b92643c',
    messagingSenderId: '420920607861',
    projectId: 'muzika-plus',
    storageBucket: 'muzika-plus.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_G-Auws0uc69CS1Fpmt4fxcp7TNYhreE',
    appId: '1:420920607861:ios:c33a711f31c5290b92643c',
    messagingSenderId: '420920607861',
    projectId: 'muzika-plus',
    storageBucket: 'muzika-plus.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs072h5jpe1nC-3dZMvxtUHjM44QYk3B0',
    appId: '1:420920607861:web:b4d71cbd37a89a6b92643c',
    messagingSenderId: '420920607861',
    projectId: 'muzika-plus',
    authDomain: 'muzika-plus.firebaseapp.com',
    storageBucket: 'muzika-plus.firebasestorage.app',
  );

}